### ISSUE TITLE
Some Problem With API 

### ISSUE THREAD

**Issue by Peken-bower** [avaire/leaderboard#18]
**Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:1256/leaderboard/894661958979178539. (Reason: CORS request did not succeed).** 

**Uncaught (in promise) TypeError: e.$router is undefined**

![error](https://user-images.githubusercontent.com/82868629/140832613-366bd15a-f1de-4d8a-9c27-e22309553481.png)

config File of Avaire 

```
web-servlet:
  metrics: true
  api-routes:
    leaderboard: true
    players: true
    guilds: true
    stats: true
  port: 1256
  authToken: 'elmrabetAbdellah'
```
